### ISSUE TITLE
Snips satelit

### ISSUE THREAD

**Issue by chkuehnel** [MrJohnZoidberg/Snips-Taschenrechner#1]
Moin, ich weiß, dass das hier eigentlich nicht passt, aber ich bin ziemlich verzweifelt auf der Suche nach einer guten Anleitung um einen Pi Zero als Satelit ans laufen zu bekommen. Hast du ne ne gute Anleitung auf Lager? Ich hab so ziemlich alles durch was die Snips Doku und das gesamte Internt hergibt...
Danke und Gruß Christian

**Comment by dominiczedler** [comment]
Ich hoffe, du hast in zwischen etwas gefunden, ich habe dein Issue leider nicht gesehen.
Hier ist die offizielle Dokumentation zu einer neuen Methode die nur einen laufenden Service benötigt (snips-satellite):
[https://docs.snips.ai/articles/platform/satellites](https://docs.snips.ai/articles/platform/satellites)
