### ISSUE TITLE
Sprachausgabe

### ISSUE THREAD

**Issue by JoergZ2** [MrJohnZoidberg/Snips-Taschenrechner#2]
Ich versuche herauszubekommen, wie man Snips zu einer Sprachausgabe auf dem Satelliten veranlassen kann. Ich höre den Quittungston für den Start einer Spracheingabe und für das Ende. Aber aus den Tutaorials bei Snips werde ich nicht schklau, wie man einen Satz (als Text oder als WAV-Datei) zur Ausgabe bringen kann. Der Rechner sagt ja das Ergenis an. Wie hast du das gemacht?

**Comment by dominiczedler** [comment]
Hallo @JoergZ2 , du hast doch meinen Code vor dir :) Möchtest du speziell was zur Ausgabe auf den Satellite-Geräten wissen, oder wie die Ausgabe allgemein auf beliebigen Geräten gemacht wird?
Im Grunde gibt es da keinen Unterschied bei der Taschenrechner-App, da sie einfach die Antwort auf die Frage mit Session-ID an Snips schickt, und Snips kümmert sich dann darum, wo die Session gerade am laufen ist und wo die Antwort ausgegeben werden soll.

**Comment by JoergZ2** [comment]
Danke! Ich habe es inzwischen herausgefunden und generiere die Antworten über TTS in meinem Python-Skript und sende sie per siteId an den Satelliten.
